"""move incident contract onto incident row

Revision ID: 003
Revises: 002
Create Date: 2026-07-30 09:26:53.879663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('partial_result', sa.JSON(), nullable=True))
    op.drop_column('extractions', 'incident_contract')
    op.add_column('incidents', sa.Column('incident_contract', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('incident_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incidents', sa.Column('incident_datetime', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incidents', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incidents', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incidents', sa.Column('civilian_injuries', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('civilian_fatalities', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('responder_injuries', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('responder_fatalities', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('people_rescued', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('people_evacuated', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('structures_destroyed', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('area_burned_ha', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('total_loss_amount', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('total_loss_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incidents', sa.Column('call_to_arrival_seconds', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('turnout_seconds_first_unit', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('travel_seconds_first_unit', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('on_scene_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'on_scene_duration_seconds')
    op.drop_column('incidents', 'travel_seconds_first_unit')
    op.drop_column('incidents', 'turnout_seconds_first_unit')
    op.drop_column('incidents', 'call_to_arrival_seconds')
    op.drop_column('incidents', 'total_loss_currency')
    op.drop_column('incidents', 'total_loss_amount')
    op.drop_column('incidents', 'area_burned_ha')
    op.drop_column('incidents', 'structures_destroyed')
    op.drop_column('incidents', 'people_evacuated')
    op.drop_column('incidents', 'people_rescued')
    op.drop_column('incidents', 'responder_fatalities')
    op.drop_column('incidents', 'responder_injuries')
    op.drop_column('incidents', 'civilian_fatalities')
    op.drop_column('incidents', 'civilian_injuries')
    op.drop_column('incidents', 'country')
    op.drop_column('incidents', 'state')
    op.drop_column('incidents', 'city')
    op.drop_column('incidents', 'incident_datetime')
    op.drop_column('incidents', 'incident_category')
    op.drop_column('incidents', 'incident_contract')
    op.add_column('extractions', sa.Column('incident_contract', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('extractions', 'partial_result')
    # ### end Alembic commands ###
