"""form templates registry and pdf upload drafts

Revision ID: 004
Revises: 003
Create Date: 2026-08-10

Two tables, both new in the contract Layer 6 template work.

`form_templates` is the registry, keyed by `form_type` and distinct from the
legacy `template` table (int PK + uploaded PDF). Its `fields` JSON column holds
the TemplateField list, each with a nested `layout`. `form_type` stays a plain
VARCHAR rather than a Postgres enum, because jurisdictions register their own
form types and those are not part of the built-in FormType enum.

`template_uploads` holds the drafts behind the PDF authoring flow: the stored
blank PDF, its page geometry, and the fields commonforms detected. Rows here
are working state, not templates. Registering a template copies the edited
fields across and keeps only the `pdf_template_ref` pointing back.

Both JSON columns use sa.JSON for consistency with migrations 001-003 and for
the SQLite test harness.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('form_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jurisdiction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agency_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('source_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pdf_template_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_form_templates_form_type'), 'form_templates', ['form_type'], unique=True)
    op.create_table('template_uploads',
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_template_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.Column('detected_fields', sa.JSON(), nullable=True),
    sa.Column('detection_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_uploads')
    op.drop_index(op.f('ix_form_templates_form_type'), table_name='form_templates')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
