name: Lint

on:
  push:
    branches: [main,development]
  pull_request:
    branches: [main, development, 'development-*']

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install linter
        run: uv pip install --system ruff==0.16.1

      - name: Run linter
        run: |
          ruff check app/ --output-format=github